/** @type {import('tailwindcss').Config} */
module.exports = {
  important: true,
  content: [
    // "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    // "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    // "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/core/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/braid-ui/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      boxShadow: {
        FilterRangePopUp: "0px 0px 6px -4px rgba(5, 89, 252, 0.12)",
        filterInputField: "0px 1px 2px rgba(16, 24, 40, 0.05)",
        filterSection: "-4px 0px 12px -4px rgba(5, 89, 252, 0.15)",
        Auth: "0px 10px 30px rgba(5, 90, 252, 0.08)",
        SideBar: "0px 10px 24px rgba(5, 90, 252, 0.08);",
        signOut: "0px 6px 24px -4px rgba(5, 89, 252, 0.15)",
        dropDownMenuSelection: "0px 6px 24px -4px rgba(5, 89, 252, 0.06)",
        form: "var(--shadow-form)",
        "form-focus": "var(--shadow-form-focus)",
        "form-error": "var(--shadow-form-error)",
      },

      fontFamily: {
        "gilroy-semi-bold": ["Gilroy-SemiBold", "sans-serif"],
        "gilroy-bold": ["Gilroy-Bold", "sans-serif"],
        "gilroy-medium": ["Gilroy-Medium", "sans-serif"],
        "avenir-regular": ["AvenirNext LT Pro Regular", "sans-serif"],
        "avenir-light": ["Avenir Next LT Pro Light", "sans-serif"],
        avenir: ["AvenirNext", "sans-serif"],
        gilroy: ["Gilroy", "sans-serif"],
      },

      colors: {
        unfocused: "rgba(0, 0, 0, 0.3)",
        "primary-50": "#E6EFFF",
        "primary-100": "#B2CCFE",
        "primary-200": "#8CB3FE",
        "primary-300": "#5890FD",
        "primary-400": "#377BFD",
        "primary-500": "#055AFC",
        "primary-600": "#0552E5",
        "primary-700": "#0440B3",
        "primary-800": "#03328B",
        "primary-900": "#02266A",

        "success-50": "#EBF9EE",
        "success-100": "#C0EECC",
        "success-200": "#A2E5B3",
        "success-300": "#77D990",
        "success-400": "#5DD27A",
        "success-500": "#34C759",
        "success-600": "#2FB551",
        "success-700": "#258D3F",
        "success-800": "#1D6D31",
        "success-900": "#165425",

        "error-50": "#FFEBEA",
        "error-100": "#FFC2BF",
        "error-200": "#FFA5A0",
        "error-300": "#FF7C74",
        "error-400": "#FF6259",
        "error-500": "#FF3B30",
        "error-600": "#E8362C",
        "error-700": "#B52A22",
        "error-800": "#8C201A",
        "error-900": "#6B1914",

        "pending-50": "#F9F6EB",
        "pending-100": "#B58F2F",

        "neutral-0": "#FFFFFF",
        "neutral-10": "#FAFBFB",
        "neutral-20": "#F5F6F7",
        "neutral-30": "#EBEDF0",
        "neutral-40": "#DFE2E6",
        "neutral-50": "#C2C7D0",
        "neutral-60": "#B3B9C4",
        "neutral-70": "#A6AEBB",
        "neutral-80": "#98A1B0",
        "neutral-90": "#8993A4",
        "neutral-100": "#7A8699",
        "neutral-200": "#6B788E",
        "neutral-300": "#5D6B82",
        "neutral-400": "#505F79",
        "neutral-500": "#42526D",
        "neutral-600": "#354764",
        "neutral-700": "#243757",
        "neutral-800": "#15294B",
        "neutral-900": "#091E42",

        "neutralVarient-0": "#FFFFFF",
        "neutralVarient-10": "#FAFBFB",
        "neutralVarient-20": "#F5F6F7",
        "neutralVarient-30": "#EBEDF0",
        "neutralVarient-40": "#DFE2E6",
        "neutralVarient-50": "#C2C7D0",
        "neutralVarient-60": "#B3B9C4",
        "neutralVarient-70": "#A6AEBB",
        "neutralVarient-80": "#98A1B0",
        "neutralVarient-90": "#8993A4",
        "neutralVarient-100": "#7A8699",
        "neutralVarient-200": "#6B788E",
        "neutralVarient-300": "#5D6B82",
        "neutralVarient-400": "#505F79",
        "neutralVarient-500": "#42526D",
        "neutralVarient-600": "#354764",
        "neutralVarient-700": "#243757",
        "neutralVarient-800": "#15294B",
        "neutralVarient-900": "#091E42",

        // braid-ui CSS variable-based colors
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          glow: "hsl(var(--primary-glow))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        form: {
          background: "hsl(var(--form-background))",
          border: "hsl(var(--form-border))",
          "border-focus": "hsl(var(--form-border-focus))",
          "border-error": "hsl(var(--form-border-error))",
          "border-success": "hsl(var(--form-border-success))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      backgroundImage: {
        "gradient-primary": "var(--gradient-primary)",
        "gradient-subtle": "var(--gradient-subtle)",
      },
    },
  },
  plugins: [
    require("tailwind-scrollbar-hide"),
    require("tailwind-scrollbar")({ nocompatible: true }),
  ],
  // variants: {
  //   scrollbar: ["rounded"],
  // },
};
