import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../core/providers/Providers";
import MuiThemeProvider from "@/core/providers/ThemeProvider";
import React, { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Braid Dashboard",
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen">
          <MuiThemeProvider>
            <Suspense>
              <Providers>{children}</Providers>
            </Suspense>
          </MuiThemeProvider>
        </div>
      </body>
    </html>
  );
}
