// TYPES
export type PaginationStateType = {
  rowCount: number;
  pageNumber: number;
  loadingPage: boolean;
};

export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sept",
  "Oct",
  "Nov",
  "Dec",
];

export const SCROLLBAR_STYLE =
  "overflow-y-auto scrollbar scrollbar-thin scrollbar-thumb-[#12A7FF] scrollbar-thumb-rounded-full scrollbar-track-[#ffffff]";

export const paginationPageSize = 100;

/// TIMEZONE
export const APP_TIMEZONE = "America/Los_Angeles";

export const ADMIN_SPECIFIC_FEATURE_MESSAGE =
  "This feature is only available for Bank";

export const ADMIN_ROLE = "admin-admin";
export const ADMIN_OPS_ROLE = "admin-ops";
export const DEVELOPER_ROLE = "developer-developer";
export const DEVELOPER_OPS_ROLE = "developer-ops";
export const CUSTOMER_ROLE = "customers";

export const ADMIN_ROUTE = [ADMIN_ROLE, ADMIN_OPS_ROLE];
export const DEVELOPER_ROUTE = [
  DEVELOPER_ROLE,
  DEVELOPER_OPS_ROLE,
  ADMIN_ROLE,
  ADMIN_OPS_ROLE,
];
export const CUSTOMER_ROUTE = [
  CUSTOMER_ROLE,
  DEVELOPER_ROLE,
  DEVELOPER_OPS_ROLE,
  ADMIN_ROLE,
  ADMIN_OPS_ROLE,
];

export const States = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

// export const TransactionType = [
//   "ADJUSTMENT_CREDIT_VC",
//   "ADJUSTMENT_DEBIT_VC",
//   "ADJUSTMENT_CREDIT_STABLE",
//   "ADJUSTMENT_DEBIT_STABLE",
//   "ACH_DEPOSIT_VC",
//   "ACH_WITHDRAWAL_VC",
//   "ACH_DEPOSIT_STABLE",
//   "ACH_WITHDRAWAL_STABLE",
//   "ACH_ORIGINATOR_CREDIT_VC",
//   "ACH_ORIGINATOR_DEBIT_VC",
//   "ACH_ORIGINATOR_CREDIT_STABLE",
//   "ACH_ORIGINATOR_DEBIT_STABLE",
//   "ACH_RECEIVER_CREDIT_VC",
//   "ACH_RECEIVER_DEBIT_VC",
//   "ACH_RECEIVER_CREDIT_STABLE",
//   "ACH_RECEIVER_DEBIT_STABLE",
//   "WIRE_ORIGINATOR_CREDIT_VC",
//   "WIRE_RECEIVER_CREDIT_VC",
//   "WIRE_ORIGINATOR_CREDIT_STABLE",
//   "WIRE_RECEIVER_CREDIT_STABLE",
//   "CARD_ACQUIRER_DEPOSIT_VC",
//   "CARD_ACQUIRER_DEPOSIT_STABLE",
//   "MVC_TO_MVC",
//   "MVC_TO_MVC_DIFF_PRODUCTS",
//   "MVC_TO_MSTABLE",
//   "MSTABLE_TO_MVC",
//   "MSTABLE_TO_MSTABLE",
//   "MSTABLE_TO_MSTABLE_DIFF_PRODUCTS",
//   "MSTABLE_TO_YSTABLE",
//   "VC_ECOMM",
//   "STABLE_ECOMM",
//   "VC_ECOMM_DIFF_PRODUCTS",
//   "STABLE_ECOMM_DIFF_PRODUCTS",
//   "STABLE_ECOMM_NOT",
//   "VC_POS",
//   "STABLE_POS",
//   "VC_POS_DIFF_PRODUCTS",
//   "STABLE_POS_DIFF_PRODUCTS",
//   "STABLE_POS_NOT",
//   "VC_MCSEND",
//   "STABLE_MCSEND",
//   "VC_RTP",
//   "STABLE_RTP",
//   "CARD_ISSUER_PREAUTH_VC",
//   "CARD_ISSUER_PURCHASE_VC",
//   "CARD_ISSUER_WITHDRAWAL_VC",
//   "CARD_ISSUER_PREAUTH_STABLE",
//   "CARD_ISSUER_PURCHASE_STABLE",
//   "CARD_ISSUER_WITHDRAWAL_STABLE",

//   "ACH_RETURNED_DEPOSIT_VC",
//   "ACH_RETURNED_WITHDRAWAL_VC",
//   "ACH_RETURNED_ORIGINATOR_CREDIT_VC",
//   "ACH_RETURNED_ORIGINATOR_DEBIT_VC",

//   "ACH_RETURNED_ADMIN_DEPOSIT_VC",
//   "ACH_RETURNED_ADMIN_WITHDRAWAL_VC",
//   "ACH_RETURNED_ADMIN_ORIGINATOR_CREDIT_VC",
//   "ACH_RETURNED_ADMIN_ORIGINATOR_DEBIT_VC",

//   "ACH_RETURNED_UNAUTH_DEPOSIT_VC",
//   "ACH_RETURNED_UNAUTH_WITHDRAWAL_VC",
//   "ACH_RETURNED_UNAUTH_ORIGINATOR_CREDIT_VC",
//   "ACH_RETURNED_UNAUTH_ORIGINATOR_DEBIT_VC",

//   "FEE_VC",
//   "FEE_ACH_VC",
//   "FEE_ACH_RETURNED_VC",
//   "FEE_MISC_VC",
//   "FEE_MONTHLY_VC",

//   "TEST_DEBIT_VC",

//   "ACH_RETURNED_NSF_ORIGINATOR_DEBIT_VC",
// ];

// export const FEE_TRANSACTION_TYPES = [
//   "ACH_RETURNED_NSF_ORIGINATOR_DEBIT_VC",
//   "VC_POS_DIFF_PRODUCTS",
//   "ACH_DEPOSIT_VC",
//   "ACH_ORIGINATOR_DEBIT_VC",
//   "TEST_DEBIT_VC",
//   "STABLE_POS_DIFF_PRODUCTS",
//   "ADJUSTMENT_DEBIT_VC",
//   "ACH_DEPOSIT_STABLE",
//   "ACH_ORIGINATOR_DEBIT_STABLE",
//   "MVC_TO_MVC",
//   "ACH_RETURED_WITHDRAWAL_VC",
//   "FEE_ACH_VC",
//   "ADJUSTMENT_DEBIT_STABLE",
//   "CARD_ACQUIRER_DEPOSIT_VC",
//   "STABLE_POS_NOT",
//   "ACH_RETURNED_DEPOSIT_VC",
//   "CARD_ISSUER_PREAUTH_STABLE",
//   "MVC_TO_MSTABLE",
//   "WIRE_ORIGINATOR_CREDIT_VC",
//   "CARD_ACQUIRER_DEPOSIT_STABLE",
//   "CARD_ISSUER_PURCHASE_VC",
//   "ACH_RECEIVER_DEBIT_VC",
//   "WIRE_ORIGINATOR_CREDIT_STABLE",
//   "MVC_TO_MVC_DIFF_PRODUCTS",
//   "VC_RTP",
//   "VC_ECOMM",
//   "CARD_ISSUER_WITHDRAWAL_VC",
//   "STABLE_ECOMM_NOT",
//   "CARD_ISSUER_PURCHASE_STABLE",
//   "ACH_RECEIVER_DEBIT_STABLE",
//   "STABLE_RTP",
//   "MSTABLE_TO_MVC",
//   "CARD_ISSUER_WITHDRAWAL_STABLE",
//   "ACH_RETURNED_UNAUTH_WITHDRAWAL_VC",
//   "ACH_RETURNED_UNAUTH_DEPOSIT_VC",
//   "ACH_RETURNED_ADMIN_ORIGINATOR_CREDIT_VC",
//   "MSTABLE_TO_MSTABLE",
//   "ACH_RECEIVER_CREDIT_VC",
//   "WIRE_RECEIVER_CREDIT_VC",
//   "VC_ECOMM_DIFF_PRODUCTS",
//   "ADJUSTMENT_CREDIT_VC",
//   "MSTABLE_TO_YSTABLE",
//   "ACH_ORIGINATOR_CREDIT_VC",
//   "ACH_RECEIVER_CREDIT_STABLE",
//   "FEE_ACH_RETURNED_VC",
//   "STABLE_ECOMM_DIFF_PRODUCTS",
//   "ADJUSTMENT_CREDIT_STABLE",
//   "VC_MCSEND",
//   "ACH_RETURNED_ADMIN_DEPOSIT_VC",
//   "ACH_ORIGINATOR_CREDIT_STABLE",
//   "ACH_RETURNED_RECEIVER_CREDIT_VC",
//   "ACH_RETURNED_ORIGINATOR_CREDIT_VC",
//   "CARD_ISSUER_PREAUTH_VC",
//   "VC_POS",
//   "ACH_RETURNED_UNAUTH_RECEIVER_CREDIT_VC",
//   "ACH_RETURNED_ADMIN_WITHDRAWAL_VC",
//   "ACH_RETURNED_UNAUTH_ORIGINATOR_CREDIT_VC",
//   "ACH_RETURNED_ADMIN_RECEIVER_CREDIT_VC",
//   "STABLE_ECOMM",
//   "ACH_WITHDRAWAL_VC",
//   "WIRE_RECEIVER_CREDIT_STABLE",
//   "ACH_WITHDRAWAL_STABLE",
//   "MSTABLE_TO_MSTABLE_DIFF_PRODUCTS",
//   "STABLE_POS",
//   "STABLE_MCSEND",
//   "FEE_MISC_VC",
// ];

export const UnauthorisedReturnCodes = ["R05", "R07", "R10", "R11", "R29"];
