version: 0.2

env:
  variables:

    # Setting the default region for bot posibilities
    AWS_PROJECT_REGION: $AWS_DEFAULT_REGION
    AWS_COGNITO_REGION: $AWS_DEFAULT_REGION
    
phases:        
  pre_build:
    on-failure: ABORT
    commands:

      # Retrieves Docker login credentials from AWS ECR for authentication using the AWS CLI.
      # Necessary because Docker doesn't natively support AWS role-based authentication.
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      # Generate the GitHub short hash, which is the first 7 chars of the long hash each commit gets.
      - GIT_SHORT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      # ToDo (this needs to be read for a .env file) setting env variables in to a file
      - envsubst '${AWS_PROJECT_REGION} ${AWS_COGNITO_REGION} ${AWS_USER_POOLS_ID} ${AWS_USER_POOLS_WEB_CLIENT_ID}' < amplifyconfiguration.json.template > src/amplifyconfiguration.json

      # ToDo (another not ideal approach)
      - envsubst '${API_URL}' < api-url.json.template > src/url.json

  build:
    on-failure: ABORT
    commands:   

      # Builds the Docker image using a specified Dockerfile.
      - |
        docker build \
          --build-arg AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID \
          --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
          --cache-from $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest \
          -f .aws/code_build/Dockerfile \
          -t app .

  post_build:
    on-failure: ABORT
    commands:
    
      #
      # Tagging
      #
      
      # Tags the built image as latest so it is easy to select the most up to date image.
      - docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      
      # Additionally, tags the image with the GitHub Commit hash - this way it is easy to find the matching commit that created the image.
      - docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:git_hash_$GIT_SHORT_HASH
      
      # Additionally, tags the image with the CodeBuild Build Number - this way it is easy to find the matching build execution to the image.
      - docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:build_$CODEBUILD_BUILD_NUMBER
      
      #
      # Pusshing
      #

      # Pushes the built Docker image to the AWS ECR repository - Latest
      - docker push --quiet $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      
      # Pushes the built Docker image to the AWS ECR repository - GitHub Commit Hash
      - docker push --quiet $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:git_hash_$GIT_SHORT_HASH
      
      # Pushes the built Docker image to the AWS ECR repository - CodeBuild Build Number.
      - docker push --quiet $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:build_$CODEBUILD_BUILD_NUMBER
      
      #
      # Updating ECS with the new image.
      #
      
      # Downloads the existing ECS task definition as a JSON file.
      - aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION_NAME --query taskDefinition > task-definition.json
      
      # Removes non-editable attributes from the task definition JSON. This simplifies updating only necessary fields.
      - jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' task-definition.json > intermediate.json

      # Updates the Docker image URI in the task definition to point to the newly pushed image in ECR.
      - jq --arg imageUri "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:git_hash_$GIT_SHORT_HASH" '.containerDefinitions[0].image = $imageUri' intermediate.json > updated-task-definition.json
      
      # Registers the updated task definition in AWS ECS.
      - aws ecs register-task-definition --cli-input-json file://updated-task-definition.json
      
      # Updates the ECS service to use the new task definition.
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $ECS_TASK_DEFINITION_NAME
